# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAppShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('token', models.CharField(default='00000000000000000000000000000000', editable=False, max_length=32)),
                ('myshopify_domain', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(default=None, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
